// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Infrastructure.Data;

#nullable disable

namespace Project.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<long>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Project.Domain.Entities.Columns", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlignContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlignItems")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundRepeat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Border")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderBottom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BorderRadius")
                        .HasColumnType("int");

                    b.Property<string>("BorderStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderTop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BorderWidth")
                        .HasColumnType("int");

                    b.Property<int?>("Bottom")
                        .HasColumnType("int");

                    b.Property<string>("BoxShadow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cursor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Display")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlexDirection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontFamily")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FontSize")
                        .HasColumnType("int");

                    b.Property<string>("FontStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontWeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gap")
                        .HasColumnType("int");

                    b.Property<string>("GridTemplateColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GridTemplateRows")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<string>("JustifyContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JustifyItems")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Left")
                        .HasColumnType("int");

                    b.Property<int?>("LetterSpacing")
                        .HasColumnType("int");

                    b.Property<float?>("LineHeight")
                        .HasColumnType("real");

                    b.Property<int?>("Margin")
                        .HasColumnType("int");

                    b.Property<int?>("MarginBottom")
                        .HasColumnType("int");

                    b.Property<int?>("MarginLeft")
                        .HasColumnType("int");

                    b.Property<string>("MarginMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MarginRight")
                        .HasColumnType("int");

                    b.Property<int?>("MarginTop")
                        .HasColumnType("int");

                    b.Property<int?>("MaxHeight")
                        .HasColumnType("int");

                    b.Property<int?>("MaxWidth")
                        .HasColumnType("int");

                    b.Property<int?>("MinHeight")
                        .HasColumnType("int");

                    b.Property<int?>("MinWidth")
                        .HasColumnType("int");

                    b.Property<int?>("Opacity")
                        .HasColumnType("int");

                    b.Property<string>("Overflow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverflowWrap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverflowX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverflowY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Padding")
                        .HasColumnType("int");

                    b.Property<int?>("PaddingBottom")
                        .HasColumnType("int");

                    b.Property<int?>("PaddingLeft")
                        .HasColumnType("int");

                    b.Property<string>("PaddingMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaddingRight")
                        .HasColumnType("int");

                    b.Property<int?>("PaddingTop")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Right")
                        .HasColumnType("int");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<string>("TextAlign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextDecoration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextShadow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Top")
                        .HasColumnType("int");

                    b.Property<string>("Transform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhiteSpace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.Property<int?>("ZIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Columns");
                });

            modelBuilder.Entity("Project.Domain.Entities.ListItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlignContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlignItems")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundRepeat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Border")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderBottom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BorderRadius")
                        .HasColumnType("int");

                    b.Property<string>("BorderStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderTop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BorderWidth")
                        .HasColumnType("int");

                    b.Property<int?>("Bottom")
                        .HasColumnType("int");

                    b.Property<string>("BoxShadow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cursor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Display")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlexDirection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontFamily")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FontSize")
                        .HasColumnType("int");

                    b.Property<string>("FontStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontWeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gap")
                        .HasColumnType("int");

                    b.Property<string>("GridTemplateColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GridTemplateRows")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Href")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JustifyContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JustifyItems")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Left")
                        .HasColumnType("int");

                    b.Property<int?>("LetterSpacing")
                        .HasColumnType("int");

                    b.Property<float?>("LineHeight")
                        .HasColumnType("real");

                    b.Property<string>("LinkType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Margin")
                        .HasColumnType("int");

                    b.Property<int?>("MarginBottom")
                        .HasColumnType("int");

                    b.Property<int?>("MarginLeft")
                        .HasColumnType("int");

                    b.Property<string>("MarginMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MarginRight")
                        .HasColumnType("int");

                    b.Property<int?>("MarginTop")
                        .HasColumnType("int");

                    b.Property<int?>("MaxHeight")
                        .HasColumnType("int");

                    b.Property<int?>("MaxWidth")
                        .HasColumnType("int");

                    b.Property<int?>("MinHeight")
                        .HasColumnType("int");

                    b.Property<int?>("MinWidth")
                        .HasColumnType("int");

                    b.Property<int?>("Opacity")
                        .HasColumnType("int");

                    b.Property<string>("Overflow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverflowWrap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverflowX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverflowY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Padding")
                        .HasColumnType("int");

                    b.Property<int?>("PaddingBottom")
                        .HasColumnType("int");

                    b.Property<int?>("PaddingLeft")
                        .HasColumnType("int");

                    b.Property<string>("PaddingMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaddingRight")
                        .HasColumnType("int");

                    b.Property<int?>("PaddingTop")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Right")
                        .HasColumnType("int");

                    b.Property<int>("SlotsId")
                        .HasColumnType("int");

                    b.Property<string>("Target")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextAlign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextDecoration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextShadow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Top")
                        .HasColumnType("int");

                    b.Property<string>("Transform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhiteSpace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.Property<int?>("ZIndex")
                        .HasColumnType("int");

                    b.Property<string>("label")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SlotsId");

                    b.ToTable("ListItems");
                });

            modelBuilder.Entity("Project.Domain.Entities.PageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WebsitesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WebsitesId");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("Project.Domain.Entities.SectionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlignContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlignItems")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundRepeat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Border")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderBottom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BorderRadius")
                        .HasColumnType("int");

                    b.Property<string>("BorderStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderTop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BorderWidth")
                        .HasColumnType("int");

                    b.Property<int?>("Bottom")
                        .HasColumnType("int");

                    b.Property<string>("BoxShadow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cursor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Display")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlexDirection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontFamily")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FontSize")
                        .HasColumnType("int");

                    b.Property<string>("FontStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontWeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gap")
                        .HasColumnType("int");

                    b.Property<string>("GridTemplateColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GridTemplateRows")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JustifyContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JustifyItems")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Left")
                        .HasColumnType("int");

                    b.Property<int?>("LetterSpacing")
                        .HasColumnType("int");

                    b.Property<float?>("LineHeight")
                        .HasColumnType("real");

                    b.Property<int?>("Margin")
                        .HasColumnType("int");

                    b.Property<int?>("MarginBottom")
                        .HasColumnType("int");

                    b.Property<int?>("MarginLeft")
                        .HasColumnType("int");

                    b.Property<string>("MarginMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MarginRight")
                        .HasColumnType("int");

                    b.Property<int?>("MarginTop")
                        .HasColumnType("int");

                    b.Property<int?>("MaxHeight")
                        .HasColumnType("int");

                    b.Property<int?>("MaxWidth")
                        .HasColumnType("int");

                    b.Property<int?>("MinHeight")
                        .HasColumnType("int");

                    b.Property<int?>("MinWidth")
                        .HasColumnType("int");

                    b.Property<int?>("Opacity")
                        .HasColumnType("int");

                    b.Property<string>("Overflow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverflowWrap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverflowX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverflowY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Padding")
                        .HasColumnType("int");

                    b.Property<int?>("PaddingBottom")
                        .HasColumnType("int");

                    b.Property<int?>("PaddingLeft")
                        .HasColumnType("int");

                    b.Property<string>("PaddingMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaddingRight")
                        .HasColumnType("int");

                    b.Property<int?>("PaddingTop")
                        .HasColumnType("int");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<int?>("PageModelId")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Right")
                        .HasColumnType("int");

                    b.Property<string>("TextAlign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextDecoration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextShadow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Top")
                        .HasColumnType("int");

                    b.Property<string>("Transform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WhiteSpace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.Property<int?>("ZIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PageModelId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("Project.Domain.Entities.Slots", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlignContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlignItems")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Autoplay")
                        .HasColumnType("bit");

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundRepeat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Border")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderBottom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BorderRadius")
                        .HasColumnType("int");

                    b.Property<string>("BorderStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BorderTop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BorderWidth")
                        .HasColumnType("int");

                    b.Property<int?>("Bottom")
                        .HasColumnType("int");

                    b.Property<string>("BoxShadow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ColumnId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Controls")
                        .HasColumnType("bit");

                    b.Property<string>("Cursor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Display")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlexDirection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontFamily")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FontSize")
                        .HasColumnType("int");

                    b.Property<string>("FontStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontWeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gap")
                        .HasColumnType("int");

                    b.Property<string>("GridTemplateColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GridTemplateRows")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Href")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JustifyContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JustifyItems")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Left")
                        .HasColumnType("int");

                    b.Property<int?>("LetterSpacing")
                        .HasColumnType("int");

                    b.Property<float?>("LineHeight")
                        .HasColumnType("real");

                    b.Property<string>("LinkType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListStyleType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Loop")
                        .HasColumnType("bit");

                    b.Property<int?>("Margin")
                        .HasColumnType("int");

                    b.Property<int?>("MarginBottom")
                        .HasColumnType("int");

                    b.Property<int?>("MarginLeft")
                        .HasColumnType("int");

                    b.Property<string>("MarginMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MarginRight")
                        .HasColumnType("int");

                    b.Property<int?>("MarginTop")
                        .HasColumnType("int");

                    b.Property<int?>("MaxHeight")
                        .HasColumnType("int");

                    b.Property<int?>("MaxWidth")
                        .HasColumnType("int");

                    b.Property<int?>("MinHeight")
                        .HasColumnType("int");

                    b.Property<int?>("MinWidth")
                        .HasColumnType("int");

                    b.Property<bool?>("Muted")
                        .HasColumnType("bit");

                    b.Property<int?>("Opacity")
                        .HasColumnType("int");

                    b.Property<string>("Orientation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Overflow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverflowWrap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverflowX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverflowY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Padding")
                        .HasColumnType("int");

                    b.Property<int?>("PaddingBottom")
                        .HasColumnType("int");

                    b.Property<int?>("PaddingLeft")
                        .HasColumnType("int");

                    b.Property<string>("PaddingMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaddingRight")
                        .HasColumnType("int");

                    b.Property<int?>("PaddingTop")
                        .HasColumnType("int");

                    b.Property<bool?>("PlaybackRate")
                        .HasColumnType("bit");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Right")
                        .HasColumnType("int");

                    b.Property<string>("Target")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextAlign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextDecoration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextShadow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Thickness")
                        .HasColumnType("int");

                    b.Property<int?>("Top")
                        .HasColumnType("int");

                    b.Property<string>("Transform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Volume")
                        .HasColumnType("float");

                    b.Property<string>("WhiteSpace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.Property<int?>("ZIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColumnId");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("Project.Domain.Entities.UserModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlock")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("LoginTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Project.Domain.Entities.Websites", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HostUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublish")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Websites");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("Project.Domain.Entities.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("Project.Domain.Entities.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Domain.Entities.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("Project.Domain.Entities.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project.Domain.Entities.Columns", b =>
                {
                    b.HasOne("Project.Domain.Entities.SectionModel", "Section")
                        .WithMany("Columns")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Project.Domain.Entities.ListItems", b =>
                {
                    b.HasOne("Project.Domain.Entities.Slots", "Slots")
                        .WithMany("Items")
                        .HasForeignKey("SlotsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("Project.Domain.Entities.PageModel", b =>
                {
                    b.HasOne("Project.Domain.Entities.Websites", "websites")
                        .WithMany("Pages")
                        .HasForeignKey("WebsitesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("websites");
                });

            modelBuilder.Entity("Project.Domain.Entities.SectionModel", b =>
                {
                    b.HasOne("Project.Domain.Entities.PageModel", null)
                        .WithMany("Sections")
                        .HasForeignKey("PageModelId");
                });

            modelBuilder.Entity("Project.Domain.Entities.Slots", b =>
                {
                    b.HasOne("Project.Domain.Entities.Columns", "columns")
                        .WithMany("Slots")
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("columns");
                });

            modelBuilder.Entity("Project.Domain.Entities.Websites", b =>
                {
                    b.HasOne("Project.Domain.Entities.UserModel", "UserModel")
                        .WithMany("Websites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("Project.Domain.Entities.Columns", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("Project.Domain.Entities.PageModel", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Project.Domain.Entities.SectionModel", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("Project.Domain.Entities.Slots", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Project.Domain.Entities.UserModel", b =>
                {
                    b.Navigation("Websites");
                });

            modelBuilder.Entity("Project.Domain.Entities.Websites", b =>
                {
                    b.Navigation("Pages");
                });
#pragma warning restore 612, 618
        }
    }
}
